# Generated by Django 2.1.1 on 2018-09-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20180911_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
